// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cctree
List cctree(DataFrame dataset, IntegerVector colname, int srule, double pvalue);
RcppExport SEXP _macs_cctree(SEXP datasetSEXP, SEXP colnameSEXP, SEXP sruleSEXP, SEXP pvalueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type colname(colnameSEXP);
    Rcpp::traits::input_parameter< int >::type srule(sruleSEXP);
    Rcpp::traits::input_parameter< double >::type pvalue(pvalueSEXP);
    rcpp_result_gen = Rcpp::wrap(cctree(dataset, colname, srule, pvalue));
    return rcpp_result_gen;
END_RCPP
}
// cmasal
List cmasal(DataFrame dataset, int MAXTERMN, int MAXTERM, int MAXITER, IntegerVector varhat, int enforce, IntegerVector number);
RcppExport SEXP _macs_cmasal(SEXP datasetSEXP, SEXP MAXTERMNSEXP, SEXP MAXTERMSEXP, SEXP MAXITERSEXP, SEXP varhatSEXP, SEXP enforceSEXP, SEXP numberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< int >::type MAXTERMN(MAXTERMNSEXP);
    Rcpp::traits::input_parameter< int >::type MAXTERM(MAXTERMSEXP);
    Rcpp::traits::input_parameter< int >::type MAXITER(MAXITERSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type varhat(varhatSEXP);
    Rcpp::traits::input_parameter< int >::type enforce(enforceSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type number(numberSEXP);
    rcpp_result_gen = Rcpp::wrap(cmasal(dataset, MAXTERMN, MAXTERM, MAXITER, varhat, enforce, number));
    return rcpp_result_gen;
END_RCPP
}
// cstree
List cstree(DataFrame dataset, IntegerVector colname, int srule);
RcppExport SEXP _macs_cstree(SEXP datasetSEXP, SEXP colnameSEXP, SEXP sruleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type colname(colnameSEXP);
    Rcpp::traits::input_parameter< int >::type srule(sruleSEXP);
    rcpp_result_gen = Rcpp::wrap(cstree(dataset, colname, srule));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_macs_cctree", (DL_FUNC) &_macs_cctree, 4},
    {"_macs_cmasal", (DL_FUNC) &_macs_cmasal, 7},
    {"_macs_cstree", (DL_FUNC) &_macs_cstree, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_macs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
