# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cctree <- function(dataset, colname, srule, pvalue) {
    .Call(`_macs_cctree`, dataset, colname, srule, pvalue)
}

cmasal <- function(dataset, MAXTERMN, MAXTERM, MAXITER, varhat, enforce, number) {
    .Call(`_macs_cmasal`, dataset, MAXTERMN, MAXTERM, MAXITER, varhat, enforce, number)
}

cstree <- function(dataset, colname, srule) {
    .Call(`_macs_cstree`, dataset, colname, srule)
}

